<?php
$title = 'Delete contendetail';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete ?</p>
<?php 
$url = $this->url('contendetail', array('action' => 'delete', 'id'=>$this->id,'ig'=>$this->igirl_id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$contendetail->id; ?>" />
  <input type="submit" name="del" value="Yes" class="btn btn-primary" />
  <input type="submit" name="del" value="No" class="btn btn-primary" />
</div>
</form>
