<?php 
	$templateISUSS = $this->basePath('/Page_Bottom_Issus/');
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Play boy Viet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Le styles -->
    <link  href="<?php echo $templateISUSS; ?>css/bootstrap.css" rel="stylesheet">
    <link  href="<?php echo $templateISUSS; ?>font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <!--[if IE 7]>
      <link rel="stylesheet"  href="<?php echo $templateISUSS; ?>css/font-awesome-ie7.min.css">
    <![endif]-->
    <link rel="stylesheet" type="text/css"  href="<?php echo $templateISUSS; ?>css/style.css" />
    
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="<?php echo $templateISUSS; ?>http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <script src="<?php echo $templateISUSS; ?>js/respond.src.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144"  href="<?php echo $templateISUSS; ?>img/sample/logo-144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"  href="<?php echo $templateISUSS; ?>img/sample/logo-114.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72"  href="<?php echo $templateISUSS; ?>img/sample/logo-72.png">
                    <link rel="apple-touch-icon-precomposed"  href="<?php echo $templateISUSS; ?>img/sample/logo-57.png">
                                   <link rel="shortcut icon"  href="<?php echo $templateISUSS; ?>img/sample/logo.png">
    
  </head>

  <body>
  
    <div class="wrapper">
      <div class="row">
        <div class="col-md-3 sidebar">
          <?php require_once 'menu.php';?>
        </div><!-- end col -->
        <div class="col-md-9 content">
         
         <?php //echo content?>
         <?php echo $this->content; ?>
          <?php // require_once 'slidePaginator.php';?>
         <!--  
          <div class="pagination-wrapper">
            <ul class="pagination">
              <li class="disabled"><span>Prev</span></li>
              <li class="active"><a  href="#none">1</a></li>
              <li><a  href="#none">2</a></li>
              <li><a  href="#none">3</a></li>
              <li><a  href="#none">4</a></li>
              <li><a  href="#none">5</a></li>
              <li><a  href="#none">Next</a></li>
            </ul>
            </div><!-- end pagination-wrapper -->
         
           
          
          
          
        </div><!-- end col -->
      </div><!-- end row -->
    </div><!-- end wrapper -->
    
    <?php require_once 'footer.php';?>
   
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="<?php echo $templateISUSS; ?>js/jquery.min.js"></script>
    <script src="<?php echo $templateISUSS; ?>js/bootstrap.js"></script>
    <script src="<?php echo $templateISUSS; ?>js/rebound.js"></script>
    <script src="<?php echo $templateISUSS; ?>js/jquery.isotope.min.js"></script>
    <script type="text/javascript">
      
      $(document).ready(function() {
        
        $('.dropdown-toggle').dropdown();
        
        var $container = $('.portfolio-wrapper');
        
        $container.imagesLoaded( function(){
          $container.isotope({
            itemSelector : '.card',
            layoutMode : 'fitRows'
          });
        });
        
        // Needed functions
        var getColWidth = function() {
          var width,
          windowWidth = $(window).width();
          if( windowWidth <= 480 ) {
            width = Math.floor( $container.width() );
          } else if( windowWidth <= 768 ) {
            width = Math.floor( $container.width() );
          } else {
            width = Math.floor( 250 );
          }
          return width;
        }

        function setWidths() {
          var colWidth = getColWidth();
          $container.children().css({ width: colWidth });
        }

    
        $(window).smartresize(function() {
          setWidths();
          $container.isotope({
            masonry: {
              columnWidth: getColWidth()
            }
          });
        });
        
        $('.filter-portfolio li a').click(function(){
          $('.filter-portfolio li.active').removeClass('active');
          $(this).parent('li').addClass('active');
          var selector = $(this).attr('data-filter');
          $container.isotope({
            filter: selector,
            masonry: {  }
          });
          return false;
        });
        // update columnWidth on window resize
        $(window).smartresize(function(){
          $container.isotope({
            // update columnWidth to a percentage of container width
            masonry: {  }
          });
        });
        
      });
      
    </script>

  </body>
</html>
