<?php 
	$templateURL = $this->basePath('/Page_Bottom_Issus/');
	var_dump($girlxinh);//die;
	$basepathview = WEB_PATH.$templateURL;
	var_dump($basepathview);
?>
 <div class="portfolio-wrapper">
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/sintel/sample-sintel-1.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Sintel at Seattle International Film Festival</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/elephants-dream/sample-elephants-1.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Elephants Dream</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/big-buck-bunny/sample-bunny-1.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Big Buck Bunny</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/sintel/sample-sintel-2.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Sintel Review</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/big-buck-bunny/sample-bunny-3.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Big Buck Bunny In CG Magazine From China</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/elephants-dream/sample-elephants-2.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Singapore, CGOverdrive And 3dsense</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/sintel/sample-sintel-3.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Sintel at Seattle International Film Festival</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/big-buck-bunny/sample-bunny-2.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Studio Harddisk Online</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/elephants-dream/sample-elephants-3.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">High Frame Rate, 4K And Stereo 3D Release</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/sintel/sample-sintel-4.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="<?php echo $basepathview; ?>">Sintel at Seattle International Film Festival</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="<?php echo $basepathview; ?>">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/big-buck-bunny/sample-bunny-1.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Big Buck Bunny</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/elephants-dream/sample-elephants-2.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Elephants Dream</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/sintel/sample-sintel-3.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Sintel at Seattle International Film Festival</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/big-buck-bunny/sample-bunny-3.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">BBB Goes Hollywood!</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $basepathview; ?>img/sample/elephants-dream/sample-elephants-1.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Elephants Dream</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
          </div><!-- end portfolio-wrapper -->