<?php
$title = 'Delete igirlxinhcom';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete ?
</p>
<?php 
$url = WEB_PATH.'/igirlxinhcom/delete/'.$igirlxinhcom->id; ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$igirlxinhcom->id; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
