<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
ul.action_admin li {
	float: left;
	list-style: none;
	padding: 0px 5px 0px 0px;
}

ul.action_admin {
	display: inline-block;
}

.circle1 {
    background-color: rgba(0,0,0,0);
    border: 5px solid rgba(0,183,229,0.9);
    opacity: .9;
    border-left: 5px solid rgba(0,0,0,0);
    border-right: 5px solid rgba(0,0,0,0);
    border-radius: 50px;
    box-shadow: 0 0 15px #2187e7;
    width: 30px;
    height: 30px;
    margin: 0 auto;
    position: relative;
    top: -50px;
    -moz-animation: spinoffPulse 1s infinite linear;
    -webkit-animation: spinoffPulse 1s infinite linear;
}

@-moz-keyframes spinPulse {
    0% {
        -moz-transform: rotate(160deg);
        opacity: 0;
        box-shadow: 0 0 1px #2187e7;
    }

    50% {
        -moz-transform: rotate(145deg);
        opacity: 1;
    }

    100% {
        -moz-transform: rotate(-320deg);
        opacity: 0;
    };
}

@-moz-keyframes spinoffPulse {
    0% {
        -moz-transform: rotate(0deg);
    }

    100% {
        -moz-transform: rotate(360deg);
    };
}

@-webkit-keyframes spinPulse {
    0% {
        -webkit-transform: rotate(160deg);
        opacity: 0;
        box-shadow: 0 0 1px #2187e7;
    }

    50% {
        -webkit-transform: rotate(145deg);
        opacity: 1;
    }

    100% {
        -webkit-transform: rotate(-320deg);
        opacity: 0;
    };
}

@-webkit-keyframes spinoffPulse {
    0% {
        -webkit-transform: rotate(0deg);
    }

    100% {
        -webkit-transform: rotate(360deg);
    };
}
</style>

<script>
function divFunction(){
	//alert("submitbutton click"); 
    $(document).ready(function() {
	        var url = $('#urlaction').val();
		    var id = $('#id').val();
		    var ig = $('#ig').val();
		    var idforeign = $('#idforeign').val();
		    var src = $('#src').val();
		    var myData = {"url":url,"id":id,"ig":ig,"idforeign":idforeign,"src":src };
		    
// 		    alert(url);
// 		    alert(id);
// 		    alert(idforeign);
// 		    alert(src);
		    
// 		    //alert(myData);
		   // return 0;
		   $("#circle1").show();
		   $("#myModal").removeClass("in");
		   $("#myModal").removeAttr("aria-hidden");
		   $("#myModal").show();
		   
		    $.ajax({
	            type:"POST",
	            url:url,
	            data:myData,
	            success: function(data){
	            	 $("#circle1").hide();
	            	          console.log(data);
	                                    },
	            error: function (data) {
	                                        console.log(data);
	                                    }


	           });
	    });
     
}



</script>


<?php
// echo '<pre>';
// print_r($this->readdetail) ;
// echo '</pre>';
?>


<?php
$igirl_id = $this->igirl_id;
if (is_array ( $this->readdetail ) and ! empty ( $this->readdetail )) {
	foreach ( $this->readdetail as $key => $detail ) {
		
		?>
<h1><?php echo $detail['title'];?></h1>
<div>
	<img alt="" src="<?php echo $detail['src'];?>">
</div>
<p>
	<strong><?php echo $detail['description'];?></strong>
</p>
<div style="display: none;"><?php echo $detail['page'];?></div>
<ul class="action_admin">
	<li><a class="btn  btn-mini  "
		href="<?php echo WEB_PATH ?>/contendetail/edit/<?php echo $detail['id'].'/ig/'.$this->id?>">Edit</a>
	</li>
	<li><a href="#myModal" role="button" class="btn" data-toggle="modal">Add
			Modol</a></li>
	<li><a class="btn  btn-mini  "
		href="<?php echo WEB_PATH ?>/contendetail/add/<?php echo $detail['id'].'/ig/'.$this->id?>">Add</a>
	</li>
	<li><a class="btn  btn-mini  "
		href="<?php echo WEB_PATH ?>/contendetail/delete/<?php echo $detail['id'].'/ig/'.$this->id;?>">Delete</a></li>
	<li><a class="btn  btn-mini  "
		href="<?php echo WEB_PATH ?>/commnet/commnet/<?php echo $detail['id'];?>">Commnet</a></li>

</ul>

<?php
	}
} else {
	die ( "Not Found Record ! " );
}

?>

<div class="circle1"></div>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"
			aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add New</h3>
	</div>
	<div class="modal-body">
		<div class="containerRT">

			<div name="contendetail"  id="contendetail">
			    <input type="hidden" name ="urlaction" id="urlaction" value="<?php echo WEB_PATH ?>/contendetail/ajaxdetail/<?php echo $detail['id'].'/ig/'.$this->id?>">
				<input name="id" id="id" type="hidden" value=""> 
				<input name="ig" id="ig" type="hidden" value="<?php echo $this->id;?>"> 
				<input name="idforeign" id="idforeign" type="hidden" value="<?php echo $this->id;?>"> 
				<label><span>Upload images</span>
				 <input name="src" id="src" type="file" required="required">
				 </label>
			</div><!-- name="contendetail"  id="contendetail" -->
	<?php /*?>		
			<script type="text/javascript" src="http://127.0.0.1:1917/plugins/ckeditor/ckeditor.js"></script>
			<script type="text/javascript">
		CKEDITOR.replace( 'description', {
			width: "900px",
			height: "300px",
			toolbar: "Full"
		} );
		</script>
		*/ ?>
		
		</div>
		<!-- class="container" -->
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		<button class="btn btn-primary" onClick="divFunction()">Save Add new</button>
	</div>
</div>
